ARG version
FROM almalinux:${version}
ARG sudheer
ARG vineela
RUN echo "the boy sudheer is {sudheer} the girl vinnela is {vineela}"
CMD ["sleep","100"]






# How can you check the version of your OS? cat /etc/*release